[package]
name = "somafm-desktop-player"
version = "0.1.0"
description = "SomaFM desktop player"
authors = ["alechko"]
license = "MIT"
repository = "https://github.com/alechko/somafm-desktop-player"
edition = "2024"
rust-version = "1.90"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.7.0", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.12.0", features = ["tray-icon"] }
tauri-plugin-log = "2"
rodio = { version = "0.22.2", default-features = false, features = ["playback"] }
symphonia = { version = "0.6.1", default-features = false, features = ["mp3"] }
ureq = "3.4.2"
souvlaki = "0.8.3"
